---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.cache # includes bowers cache
  yarn: true

matrix:
  fast_finish: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - yarn install --no-lockfile
  - bower install

script:
  - npm test

# Deploy docs to gh-pages
after_success:
  - npm run docs
  - npm run deploy
