title: The Distraction Shield
logo: /assets/img/logo.png
description: The Distraction Shield is a browser extension for blocking distractive websites.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
